---
title: "Attitude Change, Figures"
author: "Jan Lorenz"
date: "August 21, 2018"
output:
  html_document:
    df_print: paged
  pdf_document:
    latex_engine: xelatex
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(gridExtra)
library(magick)
knitr::opts_chunk$set(echo = FALSE)
# Helper functions
crop <- function(im, left = 0, top = 0, right = 0, bottom = 0) {
  d <- dim(im[[1]]); w <- d[2]; h <- d[3]
  image_crop(im, glue::glue("{w-left-right}x{h-top-bottom}+{left}+{top}"))
}
```

## Microdynamics with different theta

```{r}
ContagionVsInfoint <- function(a = -0.5, m = 1, hjust = 0, end = c(0,0,0), 
	labels = FALSE, equations = FALSE, shift = 0) {
  if (length(hjust) == 1) {hjust = rep(hjust,3)}
  ggplot() + ylim(-0.3,1) + xlim(shift-1.3,shift+3.3) + theme_void() +
  # basics
  	annotate("segment", x=(shift-1.2), y=0, xend=(shift+3.2), yend=0, color="gray") +
  	annotate("segment", x=0, y=0, xend=1, yend=0, color="red", alpha=0.5) +
  	annotate("text", x=0, y=-0.2, label="0", color="gray") +
  	annotate("segment", x=0, y=0.1, xend=0, yend=-0.1, color="gray") +
  	annotate("point", x=a, y=ifelse(a==m,0.03,0), color="blue") + 
  	annotate("point", x=m, y=ifelse(a==m,-0.03,0), color="red") +
  	annotate("text", x=a + ifelse(a==m,-0.2,0), y=0.18, label="a", color="blue") + 
  	annotate("text", x=m + ifelse(a==m,0.2,0), y=0.18, label="m", color="red") +
  	# reinforcement
  	annotate(ifelse(m==0,"point","segment"), x=a, y=0.4, xend=a+(m-0*a), yend=0.4, 
  		arrow = arrow(length=unit(0.15,"cm"))) +
  	annotate("text", x=a+end[1]*(m-0*a)+(0.5-hjust[1])*0.1, y=0.4, hjust=hjust[1],
  		label=paste0(ifelse(equations," η = 0 ",""), ifelse(labels,"(contagion)",""))) +
  	# mix
  	annotate(ifelse(0.5*a==m,"point","segment"), x=a, y=0.65, xend=a+(m-0.5*a), yend=0.65, 
  		arrow = arrow(length=unit(0.15,"cm"))) +
  	annotate("text", x=a+end[2]*(m-0.5*a)+(0.5-hjust[2])*0.1, y=0.65, hjust=hjust[2],
  		label=ifelse(equations," η = 0.5 ","")) +
  	# integration
  	annotate(ifelse(a==m,"point","segment"), x=a, y=0.9, xend=a+(m-1*a), yend=0.9, 
  		arrow = arrow(length=unit(0.15,"cm"))) +
  	# annotate("text", x=a+end[3]*(m-1*a)+(0.5-hjust[3])*0.1, y=0.9, hjust=hjust[3],
  	annotate("text", x=a+end[3]*(m-1*a), y=0.9, hjust=hjust[3],
  		label=paste0(ifelse(equations," η = 1 ",""), ifelse(labels,"(integration)","")))
}
G <- gridExtra::grid.arrange(grobs = list(
	ContagionVsInfoint(a = -0.5, m = 1, hjust = 0, end = c(1,1,1),equations=TRUE),
	ContagionVsInfoint(a = 0   , m = 1, hjust = 0, end = c(1,1,1),equations=TRUE),
	ContagionVsInfoint(a = 0.5 , m = 1, hjust = 0, end = c(1,1,1),equations=TRUE),
	ContagionVsInfoint(a = 1   , m = 1, hjust = 0, end = c(1,1,1),equations=TRUE),
	ContagionVsInfoint(a = 1.5 , m = 1, hjust = 1, end = c(0,0,1),equations=TRUE, shift=1),
	ContagionVsInfoint(a = 2   , m = 1, hjust = 1, end = c(0,1,1),equations=TRUE, shift=1),
	ContagionVsInfoint(a = 2.5 , m = 1, hjust = 1, end = c(0,1,1),equations=TRUE, shift=1),
	ContagionVsInfoint(a = 3   , m = 1, hjust = 1, end = c(0,1,1),equations=TRUE, shift=1)
	),
	ncol = 2, layout_matrix = cbind(1:4, 5:8)
)
# ggsave(filename = "FigContagionVsInfoint", plot=G, device = "png")
```

## Examples

```{r Examples}
crop_full <- function(im) crop(im, left=410, top=165, right=430, bottom=425) 
crop_histogram <- function(im) crop(im, left=1149, top=287, right=433, bottom=426)
image_read("figures_netlogo/1-A_interface.png") %>% crop_full()
image_read("figures_netlogo/1-B_interface.png") %>% crop_full()
image_read("figures_netlogo/1-C_interface.png") %>% crop_full()

image_read(paste0("figures_netlogo/1-A_interface.png")) %>% crop_histogram()
image_read(paste0("figures_netlogo/1-B_interface.png")) %>% crop_histogram()
image_read(paste0("figures_netlogo/1-C_interface.png")) %>% crop_histogram()
image_read(paste0("figures_netlogo/2-A_interface.png")) %>% crop_histogram()
image_read(paste0("figures_netlogo/2-B_interface.png")) %>% crop_histogram()
image_read(paste0("figures_netlogo/2-C_interface.png")) %>% crop_histogram()
image_read(paste0("figures_netlogo/3-A_interface.png")) %>% crop_histogram()
image_read(paste0("figures_netlogo/3-B_interface.png")) %>% crop_histogram()
image_read(paste0("figures_netlogo/3-C_interface.png")) %>% crop_histogram()
```



## NetLogo BehaviorSpace Analysis

```{r AlphaEtaTheta_BiasDiversity}

# d <- read_csv(file = "data/attitude_change delta_p2-table.csv",	skip = 6)
d <- read_csv(file = "data/attitude_change_2 AlphaEtaTheta-table.csv",	skip = 6)
g1 <- d %>% filter(eta == 0, alpha %in% c(0.1, 0.2, 0.3, 0.4, 0.5)) %>%
	rename(Bias=cum_biasmean, Diversity=cum_sd) %>% 
	gather(key="measure", value="value", Bias, Diversity) %>% 
	ggplot(aes(x = p, y = value/3.5, size =  factor(alpha), color = factor(alpha))) + 
	geom_line() + geom_point(size = 0.3) +
	facet_grid(measure ~ .) + theme_bw() +
	scale_color_manual(values=c("red","black","green","blue","violet")) +
	scale_size_manual(values=0.5*c(1,3,1,1,1)) +
	labs(x="θ (idiosyncrasy prob.)", y="", 
		title="Increase idiosyncrasy: \n Transition to unbiased diversity",
		caption="always η = 0 (affective contagion) ") +
	guides(color=guide_legend(title="α (strength)", title.position = "top"), 
		size="none") + 
	theme(legend.position = "bottom")
g2 <- d %>% filter(p  %in% c(0.1,0.05,0.01, 0.15, 0.2), alpha == 0.2) %>% 
	rename(Bias=cum_biasmean, Diversity=cum_sd) %>% 
	gather(key="measure", value="value", Bias, Diversity) %>% 
	ggplot(aes(x = eta, y = value/3.5, size = factor(p), color = factor(p)))	+ 
	geom_line() + geom_point(size = 0.3) + 
	facet_grid(measure ~ .) + theme_bw() + 
	scale_color_manual(values=c("black","red","green","blue","violet")) +
	scale_size_manual(values=0.5*c(3,1,1,1,1)) +
	labs(x="η (degree of integration)", y="", 
		title="Increase degree of integration: \n Tipping to central consensus",
		caption="always strength α = 0.2") +
	guides(color=guide_legend(title="θ (idiosyncrasy prob.)", title.position = "top"),
		size="none") + 
	theme(legend.position = "bottom")
gridExtra::grid.arrange(g1,g2, nrow=1)
```

```{r}
d %>% filter(alpha  %in% c(0.1,0.2,0.3,0.4,0.5), p == 0.1) %>% 
	rename(Bias=cum_biasmean, Diversity=cum_sd) %>% 
	gather(key="measure", value="value", Bias, Diversity) %>% 
	ggplot(aes(x = eta, y = value/3.5, size = factor(alpha), color = factor(alpha)))	+ 
	geom_line() + geom_point(size = 0.3) + 
	facet_grid(measure ~ .) + theme_bw() + 
	scale_color_manual(values=c("red","black","green","blue","violet")) +
	scale_size_manual(values=0.5*c(1,3,1,1,1)) +
	labs(x="η (degree of integration)", y="", 
		title="Increase degree of integration: \n Tipping to central consensus",
		caption="always strength θ = 0.1") +
	guides(color=guide_legend(title="α (strength)", title.position = "top"),
		size="none") + 
	theme(legend.position = "bottom")
```




